INCLUDE (FindPackageHandleStandardArgs)

SET(DIMENTIONAL_MINIMIZATION_LIBRARY_DIR "$ENV{MATH_CORE_DIR}")
SET(DIMENTIONAL_MINIMIZATION_LIBRARY_DEBUG_DIR "$ENV{MATH_CORE_DEBUG_DIR}")
SET(DIMENTIONAL_MINIMIZATION_INCLUDE_DIR "$ENV{DIMENTIONAL_MINIMIZATION_INCLUDE_DIR}")

FILE(GLOB_RECURSE DIMENTIONAL_MINIMIZATION_INCLUDE "${DIMENTIONAL_MINIMIZATION_INCLUDE_DIR}/*.h" "${DIMENTIONAL_MINIMIZATION_INCLUDE_DIR}/*.hpp")
STRING(REPLACE ";" " " DIMENTIONAL_MINIMIZATION_INCLUDE ${DIMENTIONAL_MINIMIZATION_INCLUDE})
STRING(REPLACE "${DIMENTIONAL_MINIMIZATION_INCLUDE_DIR}/" " " DIMENTIONAL_MINIMIZATION_INCLUDE ${DIMENTIONAL_MINIMIZATION_INCLUDE})
STRING(REPLACE "\\" "/" DIMENTIONAL_MINIMIZATION_INCLUDE ${DIMENTIONAL_MINIMIZATION_INCLUDE})

 FIND_LIBRARY (DIMENTIONAL_MINIMIZATION_LIBRARY
  NAMES dimentional_minimization
  PATHS "${DIMENTIONAL_MINIMIZATION_LIBRARY_DIR}"
  PATH_SUFFIXES lib
  DOC "DimentionalMinimization library")
  
  FIND_LIBRARY (DIMENTIONAL_MINIMIZATION_LIBRARY_DEBUG
  NAMES dimentional_minimization
  PATHS "${DIMENTIONAL_MINIMIZATION_LIBRARY_DIR}"
  PATH_SUFFIXES lib
  DOC "DimentionalMinimization library")
  
IF (DIMENTIONAL_MINIMIZATION_INCLUDE)
	IF (DIMENTIONAL_MINIMIZATION_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (dimentional_minimization DIMENTIONAL_MINIMIZATION_INCLUDE DIMENTIONAL_MINIMIZATION_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (dimentional_minimization DIMENTIONAL_MINIMIZATION_INCLUDE DIMENTIONAL_MINIMIZATION_LIBRARY_DEBUG)
		MESSAGE("WARNING: DIMENTIONAL_MINIMIZATION_LIBRARY = ${DIMENTIONAL_MINIMIZATION_LIBRARY}")
		MESSAGE("WARNING: DIMENTIONAL_MINIMIZATION_INCLUDE = ${DIMENTIONAL_MINIMIZATION_INCLUDE}")
	ELSE()
		MESSAGE("WARNING: DIMENTIONAL_MINIMIZATION_LIBRARY = ${DIMENTIONAL_MINIMIZATION_LIBRARY}")
	ENDIF()
ELSE()
	MESSAGE("WARNING: DIMENTIONAL_MINIMIZATION_INCLUDE = ${DIMENTIONAL_MINIMIZATION_INCLUDE}")
endif()