INCLUDE (FindPackageHandleStandardArgs)

SET(VECTOR_CORE_LIBRARY_DIR "$ENV{MATH_CORE_DIR}")
SET(VECTOR_CORE_LIBRARY_DEBUG_DIR "$ENV{MATH_CORE_DEBUG_DIR}")
SET(VECTOR_CORE_INCLUDE_DIR "$ENV{VECTOR_CORE_INCLUDE_DIR}")

FILE(GLOB_RECURSE VECTOR_CORE_INCLUDE "${VECTOR_CORE_INCLUDE_DIR}/vector_core/*.h" "${VECTOR_CORE_INCLUDE_DIR}/vector_core/*.hpp")
STRING(REPLACE ";" " " VECTOR_CORE_INCLUDE ${VECTOR_CORE_INCLUDE})

SET(VECTOR_CORE_INCLUDE_FILES "vector_core/vector_core.h vector_core/vector_core_norm.h")

 FIND_LIBRARY (VECTOR_CORE_LIBRARY
  NAMES vector_core
  PATHS "${VECTOR_CORE_LIBRARY_DIR}"
  PATH_SUFFIXES lib
  DOC "VectorCore library")
  
  FIND_LIBRARY (VECTOR_CORE_LIBRARY_DEBUG
  NAMES vector_core
  PATHS "${VECTOR_CORE_LIBRARY_DEBUG_DIR}"
  PATH_SUFFIXES lib
  DOC "VectorCore library")
  
IF (VECTOR_CORE_INCLUDE)
	IF (VECTOR_CORE_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (vector_core VECTOR_CORE_INCLUDE VECTOR_CORE_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (vector_core VECTOR_CORE_INCLUDE VECTOR_CORE_LIBRARY_DEBUG)
	ELSE()
		MESSAGE("WARNING: VECTOR_CORE_LIBRARY_DIR = ${VECTOR_CORE_LIBRARY}")
	ENDIF()
ELSE()
	MESSAGE("WARNING: VECTOR_CORE_INCLUDE_DIR = ${VECTOR_CORE_INCLUDE}")
endif()