INCLUDE (FindPackageHandleStandardArgs)

SET(MATRIX_CORE_LIBRARY_DIR "$ENV{MATH_CORE_DIR}")
SET(MATRIX_CORE_INCLUDE_DIR "$ENV{MATRIX_CORE_INCLUDE_DIR}")

FILE(GLOB_RECURSE MATRIX_CORE_INCLUDE "${MATRIX_CORE_INCLUDE_DIR}/matrix_core/*.h" "${MATRIX_CORE_INCLUDE_DIR}/matrix_core/*.hpp") 
FIND_LIBRARY (MATRIX_CORE_LIBRARY
  NAMES matrix_core
  PATHS "${MATRIX_CORE_LIBRARY_DIR}"
  PATH_SUFFIXES lib
  DOC "MatrixCore library")
  
IF (MATRIX_CORE_INCLUDE)
	IF (MATRIX_CORE_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (matrix_core MATRIX_CORE_INCLUDE MATRIX_CORE_LIBRARY)
	ELSE()
		MESSAGE("WARNING: MATRIX_CORE_LIBRARY_DIR = ${MATRIX_CORE_LIBRARY}")
	ENDIF()
ELSE()
	MESSAGE("WARNING: MATRIX_CORE_INCLUDE_DIR = ${MATRIX_CORE_INCLUDE}")
endif()