INCLUDE (FindPackageHandleStandardArgs)

SET(MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY_DIR "$ENV{MATH_CORE_DIR}")
SET(MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY_DEBUG_DIR "$ENV{MATH_CORE_DEBUG_DIR}")
SET(MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE_DIR "$ENV{MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE_DIR}")

FILE(GLOB_RECURSE MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE "${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE_DIR}/*.h" "${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE_DIR}/*.hpp")
STRING(REPLACE ";" " " MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE ${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE})
STRING(REPLACE "${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE_DIR}/" " " MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE ${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE})
STRING(REPLACE "\\" "/" MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE ${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE})

 FIND_LIBRARY (MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY
  NAMES MULTIDIMENSIONAL
  PATHS "${MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY_DIR}"
  PATH_SUFFIXES lib
  DOC "MultiDimensionalOptimization library")
  
   FIND_LIBRARY (MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY_DEBUG
  NAMES MULTIDIMENSIONAL
  PATHS "${MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY_DEBUG_DIR}"
  PATH_SUFFIXES lib
  DOC "MultiDimensionalOptimization library")
  
 MESSAGE("WARNING: MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY = ${MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY}")
  
IF (MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE)
	IF (MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (MULTIDIMENSIONAL MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS (MULTIDIMENSIONAL MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY_DEBUG)
		MESSAGE("WARNING: MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY = ${MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY}")
		MESSAGE("WARNING: MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE = ${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE}")
	ELSE()
		MESSAGE("WARNING: MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY = ${MULTIDIMENSIONAL_OPTIMIZATION_LIBRARY}")
	ENDIF()
ELSE()
	MESSAGE("WARNING: MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE = ${MULTIDIMENSIONAL_OPTIMIZATION_INCLUDE}")
endif()