function (group_files FILES_LIST GROUPING_PATH)
	foreach(f ${${FILES_LIST}})
		get_filename_component(DIR ${f} PATH)
		file(GLOB RPATH RELATIVE ${GROUPING_PATH} ${DIR})
		set(groop)
		if(RPATH)
			string(REGEX REPLACE "/" "\\\\" SUBGROUP ${RPATH})			
            set(groop ${SUBGROUP})
		endif()
		if(groop)			
			source_group(${groop} FILES ${f})
		endif()
	endforeach()
endfunction()